name: Retrieve recent blog posts
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  update--profile-readme:
    name: Update GitHub Profile README with recent blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 10
          feed_list: "https://kristhecodingunicorn.com/post/index.xml"
          template: "<tr><td>$title</td><td>$url</td></tr>"
          date_format: "mmm d, yyyy"
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "TECH-TIPS-LIST"
          feed_list: "https://kristhecodingunicorn.com/techtips/index.xml"
          date_format: "mmm dd, yyyy"
